MPR_PROCESS_MAP = {
    100: ['<100 \\Werkstck\\', 'Workpiece definition (Werkstückbeschreibung)'],
    101: ['<101 \\Kommentar\\', 'Comment (Kommentar)'],
    102: ['<102 \\BohrVert\\', 'Vertical drilling (Bohrungen vertikal)'],
    103: ['<103 \\BohrHoriz\\', 'Horizontal drilling (Bohrungen horizontal)'],
    104: ['<104 \\BohrUniv\\', 'Universal/angled (spatial) drilling (Bohrungen universal (Raumbohrungen))'],
    105: ['<105 \\Konturfraesen\\', 'Contour milling (Fräsen auf einem Konturzug)'],
    106: ['<106 \\Konturverleimen\\', 'Edge-banding along contour (Kantenanleimen auf einem Konturzug)'],
    107: ['<107 \\Buendigfraesen\\', 'Flush trimming along contour (Bündigfräsen auf einem Konturzug)'],
    108: ['<108 \\Kappen\\', 'End trimming / capping on contour element (Kappen an einem Konturzugelement)'],
    109: ['<109 \\Nuten\\', 'Grooving and sawing (Nuten und Sägen)'],
    112: ['<112 \\Tasche\\', 'Vertical pocket milling (Vertikale Tasche fräsen)'],
    113: ['<113 \\Unterflur-Fraesen\\', 'Underfloor milling (Unterflurfräsen)'],
    114: ['<114 \\Sauger\\', 'Single suction cup (Einzelsauger)'],
    115: ['<115 \\SaugerK\\', 'Cross-console suction cups (Y direction) (Konsolensauger quer (parallel zur Y-Achse))'],
    116: ['<116 \\NC-Code\\', 'Free NC-code block (freier NC-Code)'],
    117: ['<117 \\NCStop\\', 'NC stop / stop macro (NC-Stopp-Makro)'],
    118: ['<118 \\NCNeu\\', 'Technology change macro (deprecated) (Änderungsmakros (veraltet))'],
    119: ['<119 \\Polygonzug\\', 'Polygon milling (polyline/contour path) (Polygonzug fräsen)'],
    121: ['<121 \\Block\\', 'Block macro (Blockmakro)'],
    122: ['<122 \\Ablauf\\', 'Sequence macro (workflow of contour operations) (Ablaufmakro)'],
    123: ['<123 \\HTasc\\', 'Horizontal pocket milling (Horizontale Tasche fräsen)'],
    124: ['<124 \\Nut_R\\', 'Grooving in space (swiveled/angled grooving) (Nuten im Raum, geschwenktes Nuten)'],
    125: ['<125 \\Schleifen\\', 'Sanding along contour (Schleifen einer Kontur)'],
    126: ['<126 \\Abblasen\\', 'Blow-off along contour (Abblasen einer Kontur)'],
    127: ['<127 \\Klink\\', 'Corner notching (Ausklinken von Ecken)'],
    128: ['<128 \\Vert Getastet-Fraesen\\', 'Vertically probed (tactile) milling (vertikal getastetes Fräsen)'],
    129: ['<129 \\Messoriz\\', 'Measurement (Messen)'],
    130: ['<130 \\SaugerL\\', 'Long-console suction cups (X direction) (Konsolensauger längs (parallel zur X-Achse))'],
    131: ['<131 \\UfluBohr\\', 'Underfloor drilling (from below) (Unterflurbohren)'],
    132: ['<132 \\LageVermessen\\', 'Workpiece position measurement (Vermessen der Werkstücklage)'],
    133: ['<133 \\Konturfraesen\\', 'Horizontal milling along contour (Horizontales Fräsen auf einem Konturzug)'],
    134: ['<134 \\Drucken\\', 'Pressure zone along contour (Andruckzone an einer Kontur)'],
    135: ['<135 \\Heisspraegen\\', 'Hot stamping (Heissprägen)'],
    136: ['<136 \\Stegkante\\', 'Apply bridge/support edge along contour (Stegkante anbringen auf einem Konturzug)'],
    138: ['<138 \\Ritzen\\', 'Pre-scoring / scribing edge (for door rebate edge-banding) (Vorritzen einer Kante bei Türfalzverleimung)'],
    139: ['<139 \\Komponente\\', 'Component macro (Komponentenmakro)'],
    140: ['<140 \\Vektorfraesen\\', 'Vector / 5-axis milling along contour (Vektor Fräsen auf einem Konturzug (”5-Achs-Fräsen”))'],
    141: ['<141 \\VTasche\\', 'Vector pocket milling in space (Vektor Tasche fräsen im Raum)'],
    148: ['<148 \\AusTransport\\', 'Workpiece outfeed (suction carpet) (Werkstückaustransport mit Saugerteppich)'],
    149: ['<149 \\Konturfraesen mit C-Achse\\', 'Contour milling with C-axis (Konturfraesen mit C-Achse)'],
    151: ['<151 \\UflurTasche\\', 'Underfloor pocket milling (Unterflur-Tasche fräsen)'],
    152: ['<152 \\Grafischer Kommentar\\', 'Graphic comment / annotation (Grafischer Kommentar)'],
    153: ['<153 \\Universal\\', 'Universal macro (Universal Makro)'],
    154: ['<154 \\Laser-Anzeige\\', 'Laser display of contour (Anzeigen einer Kontur)'],
    157: ['<157 \\CF-Buendigfraesen\\', 'Flush trimming with CF aggregate (Bündigfräsen mit einem CF-Aggregat)'],
    158: ['<158 \\CF-Fraesen\\', 'Contour milling with CF aggregate (Konturfraesen mit einem CF-Aggregat)'],
    159: ['<159 \\CF-Leimen\\', 'Edge-banding with CF aggregate (Verleimen mit einem CF-Aggregat)'],
    161: ['<161 \\FK-Fraesen\\', 'Contour milling with form-milling aggregate (FK) (Konturfräsen mit einem Formfräsaggregat (FK))'],
    165: ['<165 \\CF-Druck\\', 'Pressure zone with CF aggregate (Andruckzone mit einem CF-Aggregat)'],
    166: ['<166 \\CF-Kappen\\', 'End trimming / capping with CF aggregate (Kappen mit einem CF-Aggregat)'],
    167: ['<167 \\CF-Schleifen\\', 'Sanding with CF aggregate (Schleifen mit einem CF-Aggregat)'],
    169: ['<169 \\CF-Station\\', 'Processing without contour with CF station (Bearbeiten ohne Kontur mit einer CF-Station)'],
    170: ['<170 \\CF-KTRStation\\', 'Contour processing with CF aggregate (KTRStation) (Bearbeiten an einer Kontur mit einem CF-Aggregat)'],
    177: ['<177 \\CFHeisspraegen\\', 'Hot stamping with CF aggregate (Heisspraegen mit einem CF-Aggregat)'],
    180: ['<180 \\Neustr\\', 'Technology change macro (Änderungsmakros)'],
    181: ['<181 \\FreiFormTasche\\', 'Freeform pocket milling (FreiFormTasche)'],
    182: ['<182 \\Gebiet\\', 'Area macro (Gebietsmakro)'],
    184: ['<184 \\Transport\\', 'Workpiece transport (gantry/portal) (Werkstücktransport mit Portal)'],
    187: ['<187 \\Extruder\\', 'Edge extruding along contour (Kantenextrudieren auf einem Konturzug)'],
    188: ['<188 \\Easyedge\\', 'Edge-banding using Easyedge edging strip part (Verleimen mit Easyedge Verleimteil auf einem Konturzug)'],
    189: ['<189 \\Kantensiegel\\', 'Edge sealing along contour (Kanten versiegeln auf einem Konturzug)'],
}